//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTdEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int IdUsers { get; set; }
        public int IdCars { get; set; }
        public int IdTariff { get; set; }
        public System.DateTime DateBooking { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual Users Users { get; set; }
    }
}
