//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTdEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public int IdStatus { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Status Status { get; set; }
    }
}
